# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bf0cde5b6893b22e55547a4254d720a204d9cfddd26b0214b7d5ee3aa999fa3536d222f465ef5fba6843626b8f5e6fc244415e6a1c9eb026b912284547c02c2

test:
  secret_key_base: 53420055cafae2a9a7bb138868d392d83034b94c135a10953b73f2fe9f4c28a1ddc53742582444201e7408b2691ea9fbaf7446b9e9817a7c43e17219510c26fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
